# Generated by Django 4.1.1 on 2022-09-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_bus_driver_number_alter_bus_driver_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_route',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
