# Generated by Django 4.1.1 on 2022-09-23 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_bus_bus_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businfo', to='home.bus'),
        ),
    ]
